
name: Auto SBOM generation


on:
  push:
    branches:
      - "dev-*"

jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/

      - name: Run ORT wrapper action
        uses: vg-leanix/sbom-scan@main
        with:
          api-token: ${{secrets.VSM_LEANIX_API_TOKEN}}
          
          

          