name: Test

on:
  push:
    branches:
      - "test"

jobs:
  build:
    name: Post Deployment
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - uses: actions/setup-python@v4
        with:
          python-version: "3.8.3"
          cache: "pip"

      - name: print envs
        run: |
          python test.py

   